# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'

AsciiComments:
    Enabled: false

Documentation:
    Enabled: false

ClassAndModuleChildren:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false
