# target_version:
#   rubocop v0.74.0
#
#   https://gist.github.com/onk/38bfbd78899d892e0e83

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "bin/**/*"
  DisplayCopNames: true

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    inject: "inject"
    reduce: "inject"

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/EmptyElse:
  EnforcedStyle: empty

Layout/ExtraSpacing:

  AllowForAlignment: true
  Exclude:
    - "db/migrate/*.rb"

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  MinBodyLength: 5

Style/HashSyntax:
  Exclude:
    - "**/*.rake"
    - "Rakefile"

Style/MultilineTernaryOperator:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/NumericLiterals:
  MinDigits: 7

Naming/PredicateName:
  NamePrefixBlacklist:
    - "is_"
    - "have_"
  NamePrefix:
    - "is_"
    - "have_"

Style/RedundantSelf:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/SignalException:
  EnforcedStyle: only_raise

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/ParallelAssignment:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/CaseIndentation:
  EnforcedStyle: 'end'
  IndentOneStep: false

Style/SingleLineMethods:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false


Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideStringInterpolation:

  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - "spec/factories/*.rb"

Style/RescueModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/Void:
  Exclude:
    - "spec/**/*.rb"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "app/models/**/*.rb"

Lint/RescueException:
  Exclude:
    - "app/tasks/task.rb"

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "db/migrate/*.rb"

Metrics/PerceivedComplexity:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/routes.rb"
    - "config/deploy.rb"
    - "config/deploy/**/*.rb"
    - "lib/tasks/**/*.rake"
  ExcludedMethods:
    - "class_methods"

Rails:
  Enabled: true

Rails/ActionFilter:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Exit:
  Exclude:
    - "app/tasks/task.rb"
