version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          PGHOST: 127.0.0.1
          PGUSER: myuser
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USERNAME: 'root'
    working_directory: ~/triphouse

    steps:
      - checkout
      
  test:
    - run:
      name: rspec
      command: rspec
workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - build         # Run build first.
      - test:         # Then run test,
          requires:   # Test requires that build passes for it to run.
            - build   # Finally, run the build job.
